# Generated by Django 2.0.3 on 2019-04-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190430_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='specialty',
            field=models.BooleanField(default=False),
        ),
    ]
