# Generated by Django 2.2 on 2019-05-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190501_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_option',
            name='size',
            field=models.CharField(choices=[('Small Regular', 'Small Regular'), ('Large Regular', 'Large Regular'), ('Small Sicilian', 'Small Sicilian'), ('Large Sicilian', 'Large Sicilian')], max_length=5),
        ),
    ]
