# Generated by Django 2.0.3 on 2019-05-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190501_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_cheese', models.BooleanField(default=False)),
                ('sub_options', models.CharField(max_length=64)),
                ('sub_sizes', models.CharField(choices=[('S', 'Small Sub'), ('L', 'Large Sub')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='size_option',
            name='size',
            field=models.CharField(choices=[('SR', 'Small Regular'), ('LR', 'Large Regular'), ('SS', 'Small Sicilian'), ('LS', 'Large Sicilian')], max_length=25),
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='orders.Sub_extra'),
        ),
    ]
