# Generated by Django 2.0.3 on 2019-05-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190502_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_option', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_options', to='orders.Sub_option'),
        ),
    ]
