# Generated by Django 2.0.3 on 2019-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190502_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='extras',
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='extras', to='orders.Sub_extra'),
        ),
    ]
