# Generated by Django 2.0.3 on 2019-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_pizza_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastas', models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Meatballs', 'Meatballs'), ('Chicken', 'Chicken')], max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
