# Generated by Django 2.0.3 on 2019-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_salad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platter_sizes', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=64)),
                ('platters', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='pasta',
            name='pastas',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Meatballs', 'Meatballs'), ('Chicken', 'Chicken')], max_length=64),
        ),
        migrations.AlterField(
            model_name='salad',
            name='salads',
            field=models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Salad w/Tuna', 'Salad w/Tuna')], max_length=64),
        ),
        migrations.AlterField(
            model_name='size_option',
            name='size',
            field=models.CharField(choices=[('SR', 'Small Regular'), ('LR', 'Large Regular'), ('SS', 'Small Sicilian'), ('LS', 'Large Sicilian')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_sizes',
            field=models.CharField(choices=[('S', 'Small Sub'), ('L', 'Large Sub')], max_length=64),
        ),
    ]
