# Generated by Django 2.0.3 on 2019-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190502_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dinner_platter',
            name='platter_sizes',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_sizes',
            field=models.CharField(choices=[('Small', 'Small Sub'), ('Large', 'Large Sub')], max_length=64),
        ),
    ]
