# Generated by Django 2.0.3 on 2019-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_blogcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
